version: '3.8'

services:
  othello:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - VITE_VERSION=${VITE_VERSION}
        - VITE_BUILD_HASH=${VITE_BUILD_HASH}
        - VITE_BUILD_BRANCH=${VITE_BUILD_BRANCH}
        - VITE_BUILD_TIME=${VITE_BUILD_TIME}
    container_name: ${CONTAINER_NAME:-othello}
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - ROOT_DIR=${ROOT_DIR:-/app}
      - HOST=${HOST}
    networks:
      - ${TRAEFIK_NETWORK:-traefik}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.othello.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.othello.tls=true"
      - "traefik.http.routers.othello.tls.certresolver=${CERT_RESOLVER:-letsencrypt}"
      - "traefik.http.services.othello.loadbalancer.server.port=3000"
      # Security headers
      - "traefik.http.middlewares.othello-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.othello-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.othello-headers.headers.customRequestHeaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.othello-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.othello-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.othello-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.othello-headers.headers.stsPreload=true"
      - "traefik.http.routers.othello.middlewares=othello-headers"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik:
    external: true