version: '3.8'

services:
  othello:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Debug configuration (disabled by default in production)
      - NODE_DEBUG_ENABLED=${NODE_DEBUG_ENABLED:-false}
      - NODE_DEBUG_DUMMY_GAME=${NODE_DEBUG_DUMMY_GAME:-false}
      - NODE_DEBUG_AUTO_PLAY=${NODE_DEBUG_AUTO_PLAY:-false}
      - NODE_DEBUG_GAME_INSPECTOR=${NODE_DEBUG_GAME_INSPECTOR:-false}
      - NODE_DEBUG_PERFORMANCE=${NODE_DEBUG_PERFORMANCE:-false}
      - REACT_APP_DEBUG_ENABLED=${REACT_APP_DEBUG_ENABLED:-false}
      - REACT_APP_DEBUG_DUMMY_GAME=${REACT_APP_DEBUG_DUMMY_GAME:-false}
      - REACT_APP_DEBUG_AUTO_PLAY=${REACT_APP_DEBUG_AUTO_PLAY:-false}
      - REACT_APP_DEBUG_GAME_INSPECTOR=${REACT_APP_DEBUG_GAME_INSPECTOR:-false}
      - REACT_APP_DEBUG_PERFORMANCE=${REACT_APP_DEBUG_PERFORMANCE:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  othello-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # Debug configuration (enabled by default in development)
      - NODE_DEBUG_ENABLED=${NODE_DEBUG_ENABLED:-true}
      - NODE_DEBUG_DUMMY_GAME=${NODE_DEBUG_DUMMY_GAME:-true}
      - NODE_DEBUG_AUTO_PLAY=${NODE_DEBUG_AUTO_PLAY:-true}
      - NODE_DEBUG_GAME_INSPECTOR=${NODE_DEBUG_GAME_INSPECTOR:-false}
      - NODE_DEBUG_PERFORMANCE=${NODE_DEBUG_PERFORMANCE:-false}
      - REACT_APP_DEBUG_ENABLED=${REACT_APP_DEBUG_ENABLED:-true}
      - REACT_APP_DEBUG_DUMMY_GAME=${REACT_APP_DEBUG_DUMMY_GAME:-true}
      - REACT_APP_DEBUG_AUTO_PLAY=${REACT_APP_DEBUG_AUTO_PLAY:-true}
      - REACT_APP_DEBUG_GAME_INSPECTOR=${REACT_APP_DEBUG_GAME_INSPECTOR:-false}
      - REACT_APP_DEBUG_PERFORMANCE=${REACT_APP_DEBUG_PERFORMANCE:-false}
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev
    restart: unless-stopped